baseURL: https://devopsdemystifie.fr/
title: DevOps Démystifié
author:
  name: Jacint BALINT
  emailname: contact@devopsdemystifie.fr

languages:
  fr:
    languageCode: fr-FR
    languageName: Français
defaultContentLanguage: fr
theme: hugo-theme-relearn

relativeURLs: true

taxonomies:
  author: authors
  tag: tags
  category: categories

params:
  themeVariant:
    - blue
    - zen-dark
  collapsibleMenu: true # Watch out for performance issues if the number of pages grow too high
  disableRootBreadcrumb: true
  images:
    - images/header.png
  